name: MooComplete
author: erikdubbelboer
current: 1.5
category: Forms
tags: [keyboard, input, autocomplete, suggest]
docs: https://github.com/ErikDubbelboer/MooComplete/blob/master/README.md
demo: http://dubbelboer.com/MooComplete/
